patternsShopping/config/routes.rb
PatternsShopping::Application.routes.draw do
  resources :shop_directors

  resources :app_configs

  resources :notifiers

   get "sessions/new"

  resources :carts

  resources :orders

  resources :lineitems

  resources :stock_products
  resources :sessions
  resources :customers
	  
  root :to => 'shop#index'
  get "shop/index"
   match '/signin',  :to => 'sessions#new'
   match '/signout', :to => 'sessions#destroy'

end

patternsShopping/app/models/shop_director.rb
class ShopDirector < ActiveRecord::Base
  # attr_accessible :title, :body
end

patternsShopping/app/controllers/shop_directors_controller.rb
class ShopDirectorsController < ApplicationController

def initialize  
   @subevents = [:join, :accessDetails, :leave]  
  end  
  def organize event  
   @subevents.each { |se| event.send(se) if event.respond_to? se }    
  end  

  # GET /shop_directors
  # GET /shop_directors.json
  def index
    @shop_directors = ShopDirector.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @shop_directors }
    end
  end
  
def builderDirector
	ed = EventDirector.new  
		ed.organize(Shop.new)  
			# Output => "Welcome to our shop :)"  
			# "We will recieve your details"
			# "You have left"
		ed.organize(Customer.new)  
			# Output => "I want to sign up"  
			# "I want to access my details"  
			# "I want to leave"
end

  # GET /shop_directors/1
  # GET /shop_directors/1.json
  def show
    @shop_director = ShopDirector.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @shop_director }
    end
  end

  # GET /shop_directors/new
  # GET /shop_directors/new.json
  def new
    @shop_director = ShopDirector.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @shop_director }
    end
  end

  # GET /shop_directors/1/edit
  def edit
    @shop_director = ShopDirector.find(params[:id])
  end

  # POST /shop_directors
  # POST /shop_directors.json
  def create
    @shop_director = ShopDirector.new(params[:shop_director])

    respond_to do |format|
      if @shop_director.save
        format.html { redirect_to @shop_director, notice: 'Shop director was successfully created.' }
        format.json { render json: @shop_director, status: :created, location: @shop_director }
      else
        format.html { render action: "new" }
        format.json { render json: @shop_director.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /shop_directors/1
  # PUT /shop_directors/1.json
  def update
    @shop_director = ShopDirector.find(params[:id])

    respond_to do |format|
      if @shop_director.update_attributes(params[:shop_director])
        format.html { redirect_to @shop_director, notice: 'Shop director was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @shop_director.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shop_directors/1
  # DELETE /shop_directors/1.json
  def destroy
    @shop_director = ShopDirector.find(params[:id])
    @shop_director.destroy

    respond_to do |format|
      format.html { redirect_to shop_directors_url }
      format.json { head :no_content }
    end
  end
end

patternsShopping/app/helpers/shop_directors_helper.rb
module ShopDirectorsHelper
end

patternsShopping/app/views/shop_directors/_form.html.erb
<%= form_for(@shop_director) do |f| %>
  <% if @shop_director.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shop_director.errors.count, "error") %> prohibited this shop_director from being saved:</h2>

      <ul>
      <% @shop_director.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

patternsShopping/app/views/shop_directors/edit.html.erb
<h1>Editing shop_director</h1>

<%= render 'form' %>

<%= link_to 'Show', @shop_director %> |
<%= link_to 'Back', shop_directors_path %>

patternsShopping/app/views/shop_directors/index.html.erb
<h1>Listing shop_directors</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @shop_directors.each do |shop_director| %>
  <tr>
    <td><%= link_to 'Show', shop_director %></td>
    <td><%= link_to 'Edit', edit_shop_director_path(shop_director) %></td>
    <td><%= link_to 'Destroy', shop_director, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Shop director', new_shop_director_path %>

patternsShopping/app/views/shop_directors/new.html.erb
<h1>New shop_director</h1>

<%= render 'form' %>

<%= link_to 'Back', shop_directors_path %>

patternsShopping/app/views/shop_directors/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_shop_director_path(@shop_director) %> |
<%= link_to 'Back', shop_directors_path %>