patternsShopping/config/routes.rb
PatternsShopping::Application.routes.draw do
  resources :shop_directors

  resources :app_configs

  resources :notifiers

   get "sessions/new"

  resources :carts

  resources :orders

  resources :lineitems

  resources :stock_products
  resources :sessions
  resources :customers
	  
  root :to => 'shop#index'
  get "shop/index"
   match '/signin',  :to => 'sessions#new'
   match '/signout', :to => 'sessions#destroy'

end

patternsShopping/app/models/notifier.rb
class Notifier < ActiveRecord::Base
  # attr_accessible :title, :body
end

patternsShopping/app/controllers/notifiers_controller.rb
class NotifiersController < ApplicationController
  # GET /notifiers
  # GET /notifiers.json
  def index
    @notifiers = Notifier.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @notifiers }
    end
  end

  # GET /notifiers/1
  # GET /notifiers/1.json
  def show
    @notifier = Notifier.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @notifier }
    end
  end

  # GET /notifiers/new
  # GET /notifiers/new.json
  def new
    @notifier = Notifier.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @notifier }
    end
  end

  # GET /notifiers/1/edit
  def edit
    @notifier = Notifier.find(params[:id])
  end

  # POST /notifiers
  # POST /notifiers.json
  def create
    @notifier = Notifier.new(params[:notifier])

    respond_to do |format|
      if @notifier.save
        format.html { redirect_to @notifier, notice: 'Notifier was successfully created.' }
        format.json { render json: @notifier, status: :created, location: @notifier }
      else
        format.html { render action: "new" }
        format.json { render json: @notifier.errors, status: :unprocessable_entity }
      end
    end
  end
  
	def update(stock_product, prices)
    puts "The Product is priced at #{prices} price, totaling #{stock_product.price} price altogether."
    puts "The Product has a total stock quantity!" if stock_product.quantity &amp;lt;= stock_product.price
  end
  
  # PUT /notifiers/1
  # PUT /notifiers/1.json
  def update
    @notifier = Notifier.find(params[:id])

    respond_to do |format|
      if @notifier.update_attributes(params[:notifier])
        format.html { redirect_to @notifier, notice: 'Notifier was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @notifier.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notifiers/1
  # DELETE /notifiers/1.json
  def destroy
    @notifier = Notifier.find(params[:id])
    @notifier.destroy

    respond_to do |format|
      format.html { redirect_to notifiers_url }
      format.json { head :no_content }
    end
  end
end

patternsShopping/app/helpers/notifiers_helper.rb
module NotifiersHelper
end

patternsShopping/app/views/notifiers/_form.html.erb
<%= form_for(@notifier) do |f| %>
  <% if @notifier.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@notifier.errors.count, "error") %> prohibited this notifier from being saved:</h2>

      <ul>
      <% @notifier.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

patternsShopping/app/views/notifiers/edit.html.erb
<h1>Editing notifier</h1>

<%= render 'form' %>

<%= link_to 'Show', @notifier %> |
<%= link_to 'Back', notifiers_path %>

patternsShopping/app/views/notifiers/index.html.erb
<h1>Listing notifiers</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @notifiers.each do |notifier| %>
  <tr>
    <td><%= link_to 'Show', notifier %></td>
    <td><%= link_to 'Edit', edit_notifier_path(notifier) %></td>
    <td><%= link_to 'Destroy', notifier, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Notifier', new_notifier_path %>

patternsShopping/app/views/notifiers/new.html.erb
<h1>New notifier</h1>

<%= render 'form' %>

<%= link_to 'Back', notifiers_path %>

patternsShopping/app/views/notifiers/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_notifier_path(@notifier) %> |
<%= link_to 'Back', notifiers_path %>